
final List<Map<String,dynamic>> dataDummy = [
  {
    "imagePath": "https://ucarecdn.com/4f782bfb-5bad-423d-9196-b3023ef65efd/UkuranFoto5.png",
    "name": "Risol Internasional",
    "rating": 4.5,
    "district": "Sawangan",
    "city": "Depok",
    "province": "Jawa Barat",
    "estimateTime": "15m - 25m",
    "avgPrice": "30K - 75k",
    "people": 2,
    "isOpen": true,
    "openHour": "10:00",
    "closeHour": "22:00",
    "isFav": false,
    "distance": 1.9
  },
  {
    "imagePath": "https://ucarecdn.com/41a1a5bb-a40f-4920-9982-b19c772b6a1e/UkuranFoto2.png",
    "name": "Shusi Yahut",
    "rating": 3.1,
    "district": "Cinere",
    "city": "Depok",
    "province": "Jawa Barat",
    "estimateTime": "15m - 25m",
    "avgPrice": "30K - 75k",
    "people": 1,
    "isOpen": true,
    "openHour": "10:00",
    "closeHour": "22:00",
    "isFav": true,
    "distance": 10.1
  },
  {
    "imagePath": "https://ucarecdn.com/41a1a5bb-a40f-4920-9982-b19c772b6a1e/UkuranFoto2.png",
    "name": "Es Segar",
    "rating": 4.1,
    "district": "Cinere",
    "city": "Depok",
    "province": "Jawa Barat",
    "estimateTime": "15m - 25m",
    "avgPrice": "5K - 10k",
    "people": 1,
    "isOpen": false,
    "openHour": "10:00",
    "closeHour": "22:00",
    "isFav": true,
    "distance": 10.1
  },
  {
    "imagePath": "https://ucarecdn.com/7b8e452e-cbed-4146-b34d-111efa8f0bc4/UkuranFoto3.png",
    "name": "Misro Pak Usro",
    "rating": 3.6,
    "district": "Cinere",
    "city": "Depok",
    "province": "Jawa Barat",
    "estimateTime": "15m - 25m",
    "avgPrice": "5K - 10k",
    "people": 1,
    "isOpen": true,
    "openHour": "10:00",
    "closeHour": "22:00",
    "isFav": false,
    "distance": 10.1
  },
  {
    "imagePath": "https://ucarecdn.com/7b8e452e-cbed-4146-b34d-111efa8f0bc4/UkuranFoto3.png",
    "name": "Misro Pak Usro",
    "rating": 3.6,
    "district": "Cinere",
    "city": "Depok",
    "province": "Jawa Barat",
    "estimateTime": "15m - 25m",
    "avgPrice": "5K - 10k",
    "people": 1,
    "isOpen": false,
    "openHour": "10:00",
    "closeHour": "22:00",
    "isFav": true,
    "distance": 10.1
  },
];